### ISSUE TITLE
Configure to set default mode

### ISSUE THREAD

**Issue by sdargutev** [dakaraphi/eclipse-plugin-commander#34]
Providing an option to set the default mode (active mode when the dialog first appears) to "Discovery" would be very nice. 

Great job!

**Comment by dakaraphi** [comment]
What would you say is the primary use case for `Discovery` as default?

1.  It is helpful when `working` mode has not yet been populated
2.  It is helpful for `Finder` in small projects where `working` mode may not be beneficial
3.  I prefer to always search everything

**Comment by sdargutev** [comment]
1. - true
2. - true
3 - true when working on a project short term... I. e. just for a couple of hours or minutes. Populating the Working mode is usually continuous thing.

**Comment by dakaraphi** [comment]
A new command is now added to the `context` menu `Settings: Toggle Default View Mode:`

Executing the command will toggle the current mode that the dialog will open as default.
