### ISSUE TITLE
Installing encountered a problem

### ISSUE THREAD

**Issue by meengit** [dakaraphi/eclipse-plugin-commander#39]
Hi @dakaraphi

Thank you very much for developing this plugin.

I tried to install it via marketplace (default procedure Eclipse > Help > Eclipse Marketplace)

I got an error because one or required items could not be found:

<img width="1004" alt="screen shot 2018-03-03 at 00 27 48" src="https://user-images.githubusercontent.com/6507355/36926988-fa8be3a4-1e7a-11e8-976e-043ff2798c06.png">

The manual installation failed as well.

I double checked the behavior to ensure I do nothing wrong. Unfortunately, I cannot find violations. Am I the only one with this issue?

* OS: macOS Sierra 10.12.6
* Eclipse: Oxygen.2 (4.7.2)
  * Build id: M20171130-0510

**Comment by dakaraphi** [comment]
I haven't seen this before.  For some reason it says it needs org.junit but can't find it.
I will look into it and get back to you.

**Comment by meengit** [comment]
Hi @dakaraphi 

Thank you very much for responding.

I reinstalled eclipse orbit which contains junit (http://download.eclipse.org/tools/orbit/downloads/drops/R20180206163158/repository).

Afterward, I was able to install the plugin without error. 

![screen shot 2018-03-05 at 11 13 14](https://user-images.githubusercontent.com/6507355/36969784-cdaeeb9a-2066-11e8-8c7b-23e34827cbe2.png)

However, the commands/key bindings are not available in Preferences > General > Key

![screen shot 2018-03-05 at 11 12 55](https://user-images.githubusercontent.com/6507355/36969801-d623dc9a-2066-11e8-9df4-8584bdb22ffd.png)

I also checked the workspace > .metadata > .log file. Unfortunately, I do not notice errors containing a reference to your plugin. 

Do you have further ideas for debugging?

**Comment by dakaraphi** [comment]
What type of install was your original Eclipse?  I would have thought all distributions already have org.junit, but maybe not.

**Comment by meengit** [comment]
I started with Eclipse Platform:

<img width="317" alt="screen shot 2018-03-05 at 22 09 51" src="https://user-images.githubusercontent.com/6507355/36999954-0708946c-20c2-11e8-9559-f0bd6418fc0b.png">

<img width="805" alt="screen shot 2018-03-05 at 22 01 49" src="https://user-images.githubusercontent.com/6507355/36999942-00630a98-20c2-11e8-957c-cca84c09309b.png">

The missing junit/orbit was my mistake – I am sorry for that.

However, the plugin is installed but not working, and I have no more error messages. That is a little bit unusual.

**Comment by dakaraphi** [comment]
ok, I'm normally installing the plugin into 'Eclipse IDE for Java Developers'
I will see if I can install into 'Eclipse Platform' and see if I can observe a problem.

When you say you have no errors, have you checked the 'Error Log' view?

**Comment by meengit** [comment]
Yes, however, I saw no entries for your plugin. Did I overlook something?
`workspace` > `.metadata` > `.log`:

```log
!SESSION 2018-03-06 23:59:52.580 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CH
Framework arguments:  -keyring ~/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring ~/.eclipse_keyring

!ENTRY org.eclipse.jface 2 0 2018-03-06 23:59:58.518
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2018-03-06 23:59:58.518
!MESSAGE A conflict occurred for ALT+COMMAND+Q P:
Binding(ALT+COMMAND+Q P,
	ParameterizedCommand(Command(org.eclipse.ui.views.showView,Show View,
		Shows a particular view,
		Category(org.eclipse.ui.category.views,Views,Commands for opening views,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5e75cf7a,
		[Parameter(org.eclipse.ui.views.showView.viewId,View,null,true), Parameter(org.eclipse.ui.views.showView.secondaryId,Secondary Id,null,true), Parameter(org.eclipse.ui.views.showView.makeFast,As FastView,null,true)],,true),[org.eclipse.core.commands.Parameterization@351c7030]),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
Binding(ALT+COMMAND+Q P,
	ParameterizedCommand(Command(org.eclipse.php.ui.explorer,PHP Script Explorer,
		Shows the Script Explorer,
		Category(org.eclipse.ui.category.views,Views,Commands for opening views,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6f12fca0,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2018-03-06 23:59:58.518
!MESSAGE A conflict occurred for ALT+COMMAND+R:
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.python.pydev.debug.setnext,Set Next Statement,
		,
		Category(org.python.pydev.ui.category.run,PyDev - Run,Python run category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@12c30824,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7d0e43d6,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)

!ENTRY org.eclipse.core.net 1 0 2018-03-07 00:00:02.364
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.oomph.setup.ui 1 0 2018-03-07 00:00:06.033
!MESSAGE Setup tasks were performed during startup updating 1996 preferences. See '/Applications/eclipse/ide-latest-released/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.oomph.setup/setup.log' for details

```

**Comment by dakaraphi** [comment]
Using the Eclipse Platform install, this is what I additionally needed to install.

1. Eclipse Orbit.  I installed all packages.
2. Eclipse Java Developer Tools

Then I was able to install Commander.

Do you have both 1 and 2 installed?  If you go to 'about eclipse' -> 'Installed Software' and search for 'commander', do you see 'Commander Feature' listed?

If it is listed, if you type 'commander' in 'quick access' does it show there?

**Comment by meengit** [comment]
Thank you very much, that solves the problem.

Together with the newly installed JDT, Commander is now available as expected.

**Comment by pzmarzly** [comment]
I had problems getting this extension to run with Eclipse Rust edition. Installing Java Developer Tools helped. @dakaraphi , could you add a note to README or Marketplace page?
